#!/bin/bash
INDIR="/raml"
OUTDIR="/out"
MANIFEST="$INDIR/release-manifest.yml"
OUTLINK="/api-console/dist/raml"
INDEXFILE="${OUTDIR}/index.html"

GENRAML=false
[[ "$1" == 'genraml' ]] && GENRAML=true

GENCSV=false
[[ "$1" == 'gencsv' ]] && GENCSV=true

NUMRAMLS=$( ls -1 ${INDIR}/*.raml )
if [[ -z "$NUMRAMLS" ]]; then
    echo -e "\nNo RAML files found under $INDIR"
    echo "Did you forget to map the volume, perhaps?"
    exit 2
fi

if $GENCSV; then
    OUTDIR="${INDIR}/dist/csv"
    mkdir -p "$OUTDIR"
    echo "Generating CSV files under dist/csv"
    /api-console/gencsv.rb "$INDIR" "$OUTDIR"
    exit
fi

echo -e "\nGenerating versioned RAML files"
if $GENRAML; then
    OUTDIR="${INDIR}/dist/raml"
    mkdir -p "$OUTDIR"
else
    rm -rf ${OUTLINK}
    [[ -d "$OUTDIR" ]] || mkdir -p "$OUTDIR"
    ln -s "$OUTDIR" "$OUTLINK"
fi
/api-console/ramlparser.rb "$INDIR" "$OUTDIR" "$MANIFEST"
[[ $? -ne 0 ]] && exit 2

NUMVERS=$( ls -1 "$OUTDIR" )
if [[ -z "$NUMVERS" ]]; then
    echo -e "\nFailed to generate versioned RAML files\n\n"
    exit 2
fi
$GENRAML && exit 0

echo -e "Generating $INDEXFILE"
echo "<html><body>" >"$INDEXFILE"

for VISIBILITY in Private Public; do
    VISVAL=$( echo "$VISIBILITY" | tr 'A-Z' 'a-z' )
    echo "<h2>${VISIBILITY} Releases</h2><ul>" >>"$INDEXFILE"
    for REL in ${OUTDIR}/releases/${VISVAL}/*; do
        [[ -d "$REL" ]] || continue
        REL=$( basename "$REL" )
        echo "<li><a href=\"/raml/releases/${VISVAL}/${REL}\">${REL}</a></li>" >>"$INDEXFILE"

        RELDIR="${OUTDIR}/releases/${VISVAL}/${REL}"
        RELINDEX="${RELDIR}/index.html"
        echo "<html><body>" >"$RELINDEX"
        for RAML in ${RELDIR}/*.raml; do
            BASENAME=$( basename "$RAML" )
            LINKNAME=$( basename "$RAML" .raml )
            echo "<a href=\"/?raml=raml/releases/${VISVAL}/${REL}/${BASENAME}\">${LINKNAME}</a><br/>" \
                >>"$RELINDEX"
        done
        echo "</body></html>" >>"$RELINDEX"
    done
    echo "</ul>" >>"$INDEXFILE"

    echo "<h2>${VISIBILITY} Versions</h2><ul>" >>"$INDEXFILE"
    for VERS in ${OUTDIR}/versions/${VISVAL}/*; do
        [[ -d "$VERS" ]] || continue
        VERS=$( basename "$VERS" )
        echo "<li><a href=\"/raml/versions/${VISVAL}/${VERS}\">Version ${VERS}</a></li>" >>"$INDEXFILE"

        VERSDIR="${OUTDIR}/versions/${VISVAL}/${VERS}"
        VERSINDEX="${VERSDIR}/index.html"
        echo "<html><body>" >"$VERSINDEX"
        for RAML in ${VERSDIR}/*.raml; do
            BASENAME=$( basename "$RAML" )
            LINKNAME=$( basename "$RAML" .raml )
            echo "<a href=\"/?raml=raml/versions/${VISVAL}/${VERS}/${BASENAME}\">${LINKNAME}</a><br/>" \
                >>"$VERSINDEX"
        done
        echo "</body></html>" >>"$VERSINDEX"
    done
    echo "</ul>" >>"$INDEXFILE"
done

echo "</body></html>" >>"$INDEXFILE"

echo -e "\nRunning: $*"
exec "$@"
