#!/bin/bash
INDIR="/raml"
OUTDIR="/out"
OUTLINK="/api-console/dist/raml"
INDEXFILE="${OUTDIR}/index.html"

GENRAML=false
[[ "$1" == 'genraml' ]] && GENRAML=true

GENCSV=false
[[ "$1" == 'gencsv' ]] && GENCSV=true

NUMRAMLS=$( ls -1 ${INDIR}/*.raml )
if [[ -z "$NUMRAMLS" ]]; then
    echo -e "\nNo RAML files found under $INDIR"
    echo "Did you forget to map the volume, perhaps?"
    exit 2
fi

if $GENCSV; then
    OUTDIR="${INDIR}/dist/csv"
    mkdir -p "$OUTDIR"
    echo "Generating CSV files under dist/csv"
    /api-console/gencsv.rb "$INDIR" "$OUTDIR"
    exit
fi

echo -e "\nGenerating versioned RAML files"
if $GENRAML; then
    OUTDIR="${INDIR}/dist/raml"
    mkdir -p "$OUTDIR"
else
    rm -rf ${OUTLINK}
    [[ -d "$OUTDIR" ]] || mkdir -p "$OUTDIR"
    ln -s "$OUTDIR" "$OUTLINK"
fi
/api-console/ramlparser.rb "$INDIR" "$OUTDIR"

NUMVERS=$( ls -1 "$OUTDIR" )
if [[ -z "$NUMVERS" ]]; then
    echo -e "\nFailed to generate versioned RAML files\n\n"
    exit 2
fi
$GENRAML && exit 0

echo -e "Generating $INDEXFILE"
echo "<html><body>" >"$INDEXFILE"

for VERS in ${OUTDIR}/*; do
    [[ -d "$VERS" ]] || continue
    VERS=$( basename "$VERS" )
    echo "<a href=\"/raml/${VERS}\">Version ${VERS}</a></br>" >>"$INDEXFILE"

    VERSDIR="${OUTDIR}/${VERS}"
    VERSINDEX="${VERSDIR}/index.html"
    echo "<html><body>" >"$VERSINDEX"
    for RAML in ${VERSDIR}/*.raml; do
        BASENAME=$( basename "$RAML" )
        LINKNAME=$( basename "$RAML" .raml )
        echo "<a href=\"/?raml=raml/${VERS}/${BASENAME}\">${LINKNAME}</a><br/>" \
            >>"$VERSINDEX"
    done
    echo "</body></html>" >>"$VERSINDEX"
done

echo "</body></html>" >>"$INDEXFILE"

echo -e "\nRunning: $*"
exec "$@"
